version: 0.2

env:
  secrets-manager:
    AWS_ACCOUNT_ID: "AWS_ACCOUNT_ID:AWS_ACCOUNT_ID"

phases:
  install:
    runtime-version:
      docker: 18
    commands:
      - echo ECR logging...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      # build
      - echo Building image...
      - docker build -t codepipeline --build-arg DB_USERNAME=${DB_USERNAME} --build-arg DB_PASSWORD=${DB_PASSWORD} --build-arg SECRET=${SECRET} .
      # Tag image
      - echo Tag image...
      - docker tag codepipeline:latest $AWS_ECR_IMAGE

  post_build:
    commands:
      # Push image
      - echo Pushing image...
      - docker push $AWS_ECR_IMAGE
      - printf '[{"name":"%s", "imageUri":"%s"}]' $CONTAINER_NAME $AWS_ECR_IMAGE > imagedefinitions.json

artifacts:
  files: imagedefinitions.json